"""Bespoke schedule-solve tests (memo §2-§3): the iterative fixed-point rate().

Determinism (I8), convergence/uniqueness (I9), centering, and basic truth recovery. Games are
generated by the Phase-2 world model so the test rides on real synthetic signal, not hand numbers.
"""

import pytest

from core.game import GameRow
from generator.simulate import Matchup, TeamParams, WorldConfig, simulate
from models.bespoke import BespokeParams, RateResult, per_game_credit, rate, rate_weekly
from models.tiers import TierWindow

TEAMS = {"STRONG", "MID", "WEAK"}
P = BespokeParams()  # strawman defaults (memo §9); tier 3 is the neutral baseline (m=p=1.0)


def round_robin_dataset(seed: int, repeats: int):
    teams = [
        TeamParams("STRONG", attack=0.6, defense=-0.4),  # true rating +1.0
        TeamParams("MID", attack=0.0, defense=0.0),       # true rating  0.0
        TeamParams("WEAK", attack=-0.4, defense=0.6),     # true rating -1.0
    ]
    pairs = [("STRONG", "MID"), ("STRONG", "WEAK"), ("MID", "WEAK")]
    schedule = [
        Matchup(week=1 + i, team=a, opponent=b)
        for i in range(repeats)
        for (a, b) in pairs
    ]
    return simulate(WorldConfig(teams=teams, schedule=schedule, seed=seed))


def test_rate_returns_a_rating_per_team():
    res = rate(round_robin_dataset(seed=1, repeats=4).games)
    assert isinstance(res, RateResult)
    assert set(res.ratings) == TEAMS


def test_I8_deterministic_and_order_independent():
    """I8: same games run twice are identical; shuffling input order changes nothing."""
    games = round_robin_dataset(seed=1, repeats=4).games
    twice_a = rate(games).ratings
    twice_b = rate(games).ratings
    shuffled = rate(list(reversed(games))).ratings
    assert twice_a == twice_b == shuffled  # byte-identical


def test_I9_converges_from_different_starting_points():
    """I9: a unique fixed point — different inits land on the same ratings (within tolerance)."""
    games = round_robin_dataset(seed=2, repeats=4).games
    from_zero = rate(games, init={t: 0.0 for t in TEAMS}).ratings
    from_wild = rate(games, init={"STRONG": 5.0, "MID": -3.0, "WEAK": 2.0}).ratings
    for t in TEAMS:
        assert from_zero[t] == pytest.approx(from_wild[t], abs=1e-6)


def test_ratings_are_centered():
    r = rate(round_robin_dataset(seed=1, repeats=4).games).ratings
    assert sum(r.values()) == pytest.approx(0.0, abs=1e-9)


def test_recovers_true_strength_order():
    """Over enough games the recovered order matches planted truth: STRONG > MID > WEAK."""
    r = rate(round_robin_dataset(seed=5, repeats=30).games).ratings
    assert r["STRONG"] > r["MID"] > r["WEAK"]


# --- tier modulators: scale the bonus/penalty only, never the floor (memo §1.2, §4) ---------


def test_tier_modulator_scales_adjustment_not_base():
    """The tier modulator m(tier)/p(tier) scales marginAdj only; base is untouched (I1/I7).

    A win-by-3 over a tier-1 opponent earns a *larger* margin bonus than the same win over the
    neutral tier-3 (m(1) > m(3) = 1.0). A loss-by-3 to a tier-1 opponent earns a *softened*
    penalty (less negative) than to tier-3 (p(1) < p(3) = 1.0). In both cases the `base` floor is
    byte-identical — the modulation lives entirely in `margin_adj`."""
    win_t1 = per_game_credit(3, 0, opp_rating=0.0, opp_tier=1, params=P)
    win_t3 = per_game_credit(3, 0, opp_rating=0.0, opp_tier=3, params=P)
    assert win_t1.base == win_t3.base                  # floor never moves
    assert win_t1.margin_adj > win_t3.margin_adj       # bonus raised for playing up

    loss_t1 = per_game_credit(0, 3, opp_rating=0.0, opp_tier=1, params=P)
    loss_t3 = per_game_credit(0, 3, opp_rating=0.0, opp_tier=3, params=P)
    assert loss_t1.base == loss_t3.base                # floor never moves
    assert loss_t1.margin_adj > loss_t3.margin_adj     # penalty softened (less negative)
    assert loss_t1.margin_adj < 0                      # ...but still a penalty: sign never flips


def test_tier3_modulator_is_neutral():
    """Tier 3 is the neutral baseline: m(3) = p(3) = 1.0, so the existing I1-I5 credit tests
    (which fix opp_tier=3) are unchanged by wiring tiers in."""
    assert P.m_for(3) == pytest.approx(1.0)
    assert P.p_for(3) == pytest.approx(1.0)


# --- rate_weekly: the tier-aware, per-week solve (memo §5) ----------------------------------


def test_tiers_populated_by_rate_weekly():
    """rate_weekly walks weeks in order and returns a RateResult whose `tiers` dict covers every
    team that played (populated from the final week's natural-gap detection)."""
    res = rate_weekly(round_robin_dataset(seed=1, repeats=5).games)
    assert isinstance(res, RateResult)
    assert set(res.tiers) == TEAMS
    assert all(isinstance(t, int) and t >= 1 for t in res.tiers.values())


def test_rate_weekly_is_deterministic_and_order_independent():
    """I8 for the per-week solve: same games, any input order → byte-identical ratings + tiers."""
    games = round_robin_dataset(seed=3, repeats=5).games
    a = rate_weekly(games)
    b = rate_weekly(list(reversed(games)))
    assert a.ratings == b.ratings
    assert a.tiers == b.tiers


# --- I13: the frozen window damps a single-week tier blip (memo §5, brief §7 scenario 13) ----
#
# A deterministic, hand-built season (no RNG → I8). Three clear strata: E1/E2 elite, M1/M2 mid,
# BLIP + F1/F2 the field. BLIP is normally a tier-3 team. In the *blip* world it demolishes both
# elites in week 4, so its cumulative rating steps up and its week-4 finalized tier blips to tier 2
# (week 4 is the most recent finalized week before SUBJECT plays it). SUBJECT plays BLIP exactly
# once — a 3-goal win in week 5 — so SUBJECT's only winning attribution entry is that game, and its
# `margin_adj` is exactly `m(frozen_tier(BLIP)) * win_bonus["3"]`: a clean readout of the credit the
# blip lets BLIP confer. tier_count is pinned to 3 for a deterministic, non-degenerate band split.


def _g(team: str, opp: str, gf: int, ga: int, week: int) -> GameRow:
    return GameRow(week=week, date="2025-10-06", time="10:45", team=team, opponent=opp,
                   goals_team=gf, goals_opponent=ga)


def _i13_world(blip: bool) -> list[GameRow]:
    games: list[GameRow] = []
    for w in range(1, 5):
        games += [_g("E1", "F1", 8, 0, w), _g("E2", "F2", 8, 0, w),
                  _g("E1", "M1", 5, 0, w), _g("E2", "M2", 5, 0, w)]
        games += [_g("M1", "F1", 5, 0, w), _g("M2", "F2", 5, 0, w),
                  _g("M1", "F2", 5, 0, w), _g("M2", "F1", 5, 0, w)]
        if blip and w == 4:  # the one-week blip: BLIP crushes the elites
            games += [_g("BLIP", "E1", 10, 0, w), _g("BLIP", "E2", 10, 0, w),
                      _g("BLIP", "M1", 10, 0, w), _g("BLIP", "M2", 10, 0, w)]
        else:  # normal week: BLIP is the field, losing to mids and elites
            games += [_g("E1", "BLIP", 8, 0, w), _g("E2", "BLIP", 8, 0, w),
                      _g("M1", "BLIP", 6, 0, w), _g("M2", "BLIP", 6, 0, w)]
    games += [_g("SUBJECT", "BLIP", 3, 0, 5)]  # SUBJECT's lone game: a 3-goal win over BLIP
    return games


def _subject_win_credit(games: list[GameRow], *, max_window: int) -> float:
    """The margin_adj SUBJECT earns for its single win over BLIP, under a given window length."""
    res = rate_weekly(games, tier_count=3, max_window=max_window)  # shipped rho_tier default (0.2)
    wins = [b for b in res.per_game_attribution["SUBJECT"] if b.base == P.win]
    assert len(wins) == 1  # SUBJECT wins exactly once (over BLIP)
    return wins[0].margin_adj


def _blip_tier_sequence(games: list[GameRow]) -> list[int]:
    """BLIP's finalized tier, week by week — reconstructed purely from the public rate_weekly by
    re-running it on the games through each week (its `tiers` are the last week's detection)."""
    weeks = sorted({g.week for g in games})
    return [rate_weekly([g for g in games if g.week <= w], tier_count=3).tiers["BLIP"] for w in weeks]


def test_I13_blip_bounded_with_4week_window():
    """I13: with a 4-week window the credit a blipping opponent confers stays bounded — far closer
    to the pre-blip baseline than if the blip had been taken at face value (frozen as tier 1)."""
    baseline = _subject_win_credit(_i13_world(blip=False), max_window=4)  # BLIP at its true tier 3
    credit_w4 = _subject_win_credit(_i13_world(blip=True), max_window=4)  # blip, damped by window
    credit_if_tier1 = P.m_for(1) * P.win_bonus["3"]  # the un-damped extreme: BLIP frozen as tier 1
    assert abs(credit_w4 - baseline) < abs(credit_if_tier1 - baseline)


def test_I13_single_week_window_whipsaws():
    """I13 (the comparative half): a single-week freeze (window=1) swings the conferred credit more
    than the 4-week window, which damps it. This is the brief §7 scenario-13 window sweep in miniature."""
    baseline = _subject_win_credit(_i13_world(blip=False), max_window=4)
    credit_w4 = _subject_win_credit(_i13_world(blip=True), max_window=4)
    credit_w1 = _subject_win_credit(_i13_world(blip=True), max_window=1)
    swing_w4 = abs(credit_w4 - baseline)
    swing_w1 = abs(credit_w1 - baseline)
    assert swing_w1 > swing_w4


def test_I13_consistency_low_for_volatile_opponent():
    """I13 (the self-signal): an opponent whose tier moves over the window reads low consistency,
    so its volatility is itself exposed. BLIP's finalized tier shifts across the blip season; fed
    through the window, its consistency sits well below the steady-team value of 1.0."""
    seq = _blip_tier_sequence(_i13_world(blip=True))
    assert len(set(seq)) > 1  # the blip really did move BLIP's finalized tier
    window = TierWindow(max_weeks=4)
    for w, tier in enumerate(seq, start=1):
        window.add_week(w, {"BLIP": tier})
    assert window.consistency("BLIP") < 0.5


# --- recency makes a one-week blip a transient, not a permanent tier step (memo §2; TASK-06) ---
#
# The same strata as _i13_world, but BLIP keeps playing its normal (field-level) schedule for the
# whole season and blips for exactly one week. Because the per-week solve now aggregates with recency
# weighting AND keeps accumulating BLIP's later ordinary results, BLIP's inflated blip-week games no
# longer hold its cumulative rating up: its finalized tier spikes during the blip and then settles
# back to its pre-blip baseline. This is the behaviour the TASK-05 hand-off flagged recency would
# unlock — the per-week tier reads a blip as a transient, not a permanent step.


def _blip_decay_world(weeks: int, blip_week: int) -> list[GameRow]:
    """A full-season strata world (E1/E2 elite, M1/M2 mid, BLIP + F1/F2 field) where BLIP plays its
    normal field schedule every week and demolishes the elites/mids in exactly `blip_week`."""
    games: list[GameRow] = []
    for w in range(1, weeks + 1):
        games += [_g("E1", "F1", 8, 0, w), _g("E2", "F2", 8, 0, w),
                  _g("E1", "M1", 5, 0, w), _g("E2", "M2", 5, 0, w)]
        games += [_g("M1", "F1", 5, 0, w), _g("M2", "F2", 5, 0, w),
                  _g("M1", "F2", 5, 0, w), _g("M2", "F1", 5, 0, w)]
        if w == blip_week:  # the one-week blip: BLIP crushes the elites and mids
            games += [_g("BLIP", "E1", 10, 0, w), _g("BLIP", "E2", 10, 0, w),
                      _g("BLIP", "M1", 10, 0, w), _g("BLIP", "M2", 10, 0, w)]
        else:  # normal week: BLIP is the field, losing to mids and elites
            games += [_g("E1", "BLIP", 8, 0, w), _g("E2", "BLIP", 8, 0, w),
                      _g("M1", "BLIP", 6, 0, w), _g("M2", "BLIP", 6, 0, w)]
    return games


def test_blip_decays_in_per_week_tier_with_recency():
    """A one-week blip in an opponent that keeps playing is a transient: BLIP's finalized tier spikes
    in the blip week then returns to its pre-blip baseline as later ordinary games accumulate. The
    post-blip tier ends closer to the baseline than to the blip-week tier — not a permanent step."""
    seq = _blip_tier_sequence(_blip_decay_world(weeks=9, blip_week=4))  # shipped recency default (0.2)
    baseline = seq[2]          # week 3: BLIP's settled pre-blip tier (the field)
    blip_tier = seq[3]         # week 4: the blip week — its finalized tier spikes (lower number)
    post_blip = seq[-1]        # the final week: well after the blip
    assert blip_tier < baseline                                   # the blip really moved the tier up
    assert abs(post_blip - baseline) < abs(blip_tier - baseline)  # it decayed back toward baseline
