"""Bespoke schedule-solve tests (memo §2-§3): the iterative fixed-point rate().

Determinism (I8), convergence/uniqueness (I9), centering, and basic truth recovery. Games are
generated by the Phase-2 world model so the test rides on real synthetic signal, not hand numbers.
"""

import pytest

from generator.simulate import Matchup, TeamParams, WorldConfig, simulate
from models.bespoke import RateResult, rate

TEAMS = {"STRONG", "MID", "WEAK"}


def round_robin_dataset(seed: int, repeats: int):
    teams = [
        TeamParams("STRONG", attack=0.6, defense=-0.4),  # true rating +1.0
        TeamParams("MID", attack=0.0, defense=0.0),       # true rating  0.0
        TeamParams("WEAK", attack=-0.4, defense=0.6),     # true rating -1.0
    ]
    pairs = [("STRONG", "MID"), ("STRONG", "WEAK"), ("MID", "WEAK")]
    schedule = [
        Matchup(week=1 + i, team=a, opponent=b)
        for i in range(repeats)
        for (a, b) in pairs
    ]
    return simulate(WorldConfig(teams=teams, schedule=schedule, seed=seed))


def test_rate_returns_a_rating_per_team():
    res = rate(round_robin_dataset(seed=1, repeats=4).games)
    assert isinstance(res, RateResult)
    assert set(res.ratings) == TEAMS


def test_I8_deterministic_and_order_independent():
    """I8: same games run twice are identical; shuffling input order changes nothing."""
    games = round_robin_dataset(seed=1, repeats=4).games
    twice_a = rate(games).ratings
    twice_b = rate(games).ratings
    shuffled = rate(list(reversed(games))).ratings
    assert twice_a == twice_b == shuffled  # byte-identical


def test_I9_converges_from_different_starting_points():
    """I9: a unique fixed point — different inits land on the same ratings (within tolerance)."""
    games = round_robin_dataset(seed=2, repeats=4).games
    from_zero = rate(games, init={t: 0.0 for t in TEAMS}).ratings
    from_wild = rate(games, init={"STRONG": 5.0, "MID": -3.0, "WEAK": 2.0}).ratings
    for t in TEAMS:
        assert from_zero[t] == pytest.approx(from_wild[t], abs=1e-6)


def test_ratings_are_centered():
    r = rate(round_robin_dataset(seed=1, repeats=4).games).ratings
    assert sum(r.values()) == pytest.approx(0.0, abs=1e-9)


def test_recovers_true_strength_order():
    """Over enough games the recovered order matches planted truth: STRONG > MID > WEAK."""
    r = rate(round_robin_dataset(seed=5, repeats=30).games).ratings
    assert r["STRONG"] > r["MID"] > r["WEAK"]
